---

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS
      when: never
    - if: $CI_COMMIT_BRANCH
    - if: $CI_COMMIT_REF_PROTECTED == "true"

stages:
  - build
  - test
  - release

variables:
  VERSION: 0.4.0
  CI_JOB_USER: gitlab-ci-token
  DOCKER_TLS_CERTDIR: '' # disable TLS
  DOCKER_OPTS: ${DOCKER_OPTS} --registry-mirror=https://mirror.gcr.io
  FF_SCRIPT_SECTIONS: true

default:
  tags:
    - schedmd-runners

.template:
  image: docker:latest
  services:
    - docker:dind

include:
  - local: .gitlab/ci/build.yml
  - local: .gitlab/ci/test.yml
  - local: .gitlab/ci/release.yml
