{{- /*
SPDX-FileCopyrightText: Copyright (C) SchedMD LLC.
SPDX-License-Identifier: Apache-2.0
*/}}

{{- if .Values.accounting.enabled }}
{{- $podMetadata := .Values.accounting.metadata | default dict -}}
{{- $podSpec := .Values.accounting.podSpec | default dict -}}
{{- $imagePullSecrets := concat list ($podSpec.imagePullSecrets | default list) (.Values.imagePullSecrets | default list) -}}
{{- $_ := set $podSpec "imagePullSecrets" $imagePullSecrets -}}
{{- $priorityClassName := $podSpec.priorityClassName | default .Values.priorityClassName -}}
{{- $_ := set $podSpec "priorityClassName" $priorityClassName -}}
{{- $podTemplate := dict "metadata" $podMetadata "spec" $podSpec -}}
apiVersion: slinky.slurm.net/v1beta1
kind: Accounting
metadata:
  name: {{ include "slurm.fullname" . }}
  namespace: {{ include "slurm.namespace" . }}
  labels:
    {{- include "slurm.labels" . | nindent 4 }}
spec:
{{- if .Values.accounting.external }}
  external: {{ .Values.accounting.external }}
  {{- with .Values.accounting.externalConfig }}
  externalConfig:
    {{- toYaml . | nindent 4 }}
  {{- end }}{{- /* with .Values.accounting.externalConfig */}}
{{- else }}{{- /* if .Values.accounting.external */}}
  slurmKeyRef:
    {{- if .Values.slurmKeyRef }}
    {{- toYaml .Values.slurmKeyRef | nindent 4 }}
    {{- else }}
    name: {{ include "slurm.authSlurmRef.name" . }}
    key: {{ include "slurm.authSlurmRef.key" . }}
    {{- end }}{{- /* if .Values.slurmKeyRef */}}
  jwtHs256KeyRef:
    {{- if .Values.jwtHs256KeyRef }}
    {{- toYaml .Values.jwtHs256KeyRef | nindent 4 }}
    {{- else }}
    name: {{ include "slurm.authJwtHs256Ref.name" . }}
    key: {{ include "slurm.authJwtHs256Ref.key" . }}
    {{- end }}{{- /* if .Values.jwtHs256KeyRef */}}
  {{- if (include "slurm.accounting.extraConf" .) }}
  extraConf: |
    {{- include "slurm.accounting.extraConf" . | nindent 4 }}
  {{- end }}{{- /* if (include "slurm.accounting.extraConf" .) */}}
  slurmdbd:
    {{- $_ := set .Values.accounting.slurmdbd "imagePullPolicy" (default $.Values.imagePullPolicy .Values.accounting.slurmdbd.imagePullPolicy) -}}
    {{- include "format-container" .Values.accounting.slurmdbd | nindent 4 }}
  {{- include "format-podTemplate" $podTemplate | nindent 2 }}
  {{- with .Values.accounting.storageConfig }}
  storageConfig:
    {{- toYaml . | nindent 4 }}
  {{- end }}{{- /* with .Values.accounting.storageConfig */}}
  {{- include "format-service" .Values.accounting.service | nindent 2 }}
{{- end }}{{- /* if .Values.accounting.enabled */}}
{{- end }}{{- /* if .Values.accounting.external */}}
