---
apiVersion: v2
kubeVersion: ">= 1.29.0-0"

name: slurm
description: Slurm Cluster
type: application
appVersion: "25.11"
version: 1.0.0

annotations:
  license: Apache-2.0

home: https://slurm.schedmd.com/
icon: https://github.com/SlinkyProject/docs/blob/main/docs/_static/images/slurm-square-500.png

sources:
  - https://github.com/SchedMD/slurm
  - https://github.com/SlinkyProject/containers
  - https://github.com/togethercomputer/slurm-operator

maintainers:
  - name: SchedMD LLC.
    email: slinky@schedmd.com
    url: https://support.schedmd.com/
